const CardData = [
  { id: 1, symbol: "bi bi-cloud-sun" },
  { id: 2, symbol: "bi bi-brightness-high" },
  { id: 3, symbol: "bi bi-sunset" },
  { id: 4, symbol: "bi bi-9-circle" },
  { id: 5, symbol: "bi bi-8-circle" },
  { id: 6, symbol: "bi bi-7-circle" },
  { id: 7, symbol: "bi bi-6-circle" },
  { id: 8, symbol: "bi bi-5-circle" },
  { id: 9, symbol: "bi bi-4-circle" },
  { id: 10, symbol: "bi bi-3-circle" },
  { id: 11, symbol: "bi bi-2-circle" },
  { id: 12, symbol: "bi bi-1-circle" },
  { id: 13, symbol: "bi bi-cloud-sun" },
  { id: 14, symbol: "bi bi-brightness-high" },
  { id: 15, symbol: "bi bi-sunset" },
  { id: 16, symbol: "bi bi-9-circle" },
  { id: 17, symbol: "bi bi-8-circle" },
  { id: 18, symbol: "bi bi-7-circle" },
  { id: 19, symbol: "bi bi-6-circle" },
  { id: 20, symbol: "bi bi-5-circle" },
  { id: 21, symbol: "bi bi-4-circle" },
  { id: 22, symbol: "bi bi-3-circle" },
  { id: 23, symbol: "bi bi-2-circle" },
  { id: 24, symbol: "bi bi-1-circle" },
  { id: 25, symbol: "bi bi-cloud-sun" },
  { id: 26, symbol: "bi bi-brightness-high" },
  { id: 27, symbol: "bi bi-sunset" },
  { id: 28, symbol: "bi bi-9-circle" },
  { id: 29, symbol: "bi bi-8-circle" },
  { id: 30, symbol: "bi bi-7-circle" },
  { id: 31, symbol: "bi bi-6-circle" },
  { id: 32, symbol: "bi bi-5-circle" },
  { id: 33, symbol: "bi bi-4-circle" },
  { id: 34, symbol: "bi bi-3-circle" },
  { id: 35, symbol: "bi bi-2-circle" },
  { id: 36, symbol: "bi bi-1-circle" },
];

export default CardData;
